# Generated by Django 4.2.7 on 2023-11-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('UNP', 'UnPublished'), ('CSN', 'Coming Soon')], default='UNP', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('authors', models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('title', models.CharField(max_length=250)),
                ('is_free', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.course')),
            ],
            options={
                'verbose_name': 'course class',
                'verbose_name_plural': 'classes',
                'db_table': 'course_class',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribed_courses', through='courses.CourseSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
